name: Build CV

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Build CV HTML
        run: |
          mkdir -p build
          cp style.css build/

          pandoc -s cv.tex -o build/cv.html --metadata title="Kiran De Roy CV" --css=style.css

          cp template.html build/
          cp projects.html build/

          sed '/{{content}}/{ 
          r build/cv.html 
          d
          }' build/template.html > build/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build
