name: Build CV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install dependencies (Pandoc + LaTeX)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      # Convert LaTeX to HTML
      - name: Convert LaTeX to HTML
        run: |
          mkdir -p build
          cp style.css build/
          pandoc -s cv.tex -o build/index.html --metadata title="Kiran De Roy CV" --css=style.css

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build
